[project]
name = "edgar"
version = "1.0.1"
description = "Enrichment Driven GrAph Reeasoner"
authors = ["Chris Bizon <cbizon@renci.org>"]
license = "MIT"
readme = "README.md"
homepage = "https://answercoalesce-test.apps.renci.org/query"
repository = "https://github.com/ranking-agent/edgar.git"

[tool.poetry]
# Additional Poetry-specific configuration here

[tool.poetry.dependencies]
python = ">=3.12.4,<4.0"

